apiVersion: v1
kind: Pod
metadata:
  name: busybox{{ randAlphaNum 5 | nospace }}
  labels:
    app.kubernetes.io/name: busybox
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ["wget"]
      args: ['http://{{ include "chartname.appQualifiedName" . }}:80 > wget.txt']