apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup
  labels:
    app: meetup
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: meetup
  template:
    metadata:
      labels:
        app: meetup
    spec:
      containers:
        - name: meetup
          image: "timdaha/cn_meetup_demo_frontend:1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
