apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-2-frontend-svc
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
