apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartname.appQualifiedName" . }}-svc
  labels:
    app: {{ include "chartname.appName" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "chartname.appName" . }}
